apiVersion: v1
kind: Secret
metadata:
  name: webauthn-secret
  namespace: webauthn
type: Opaque
stringData:
  SECRET: secret
  DATA: /.data

---

kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: webauthn
  namespace: webauthn
  annotations:
    # nginx.ingress.kubernetes.io/enable-cors: "true"
    # nginx.ingress.kubernetes.io/cors-expose-headers: "*"
spec:
  ingressClassName: nginx
  rules:
    - host: webauthn-example.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webauthn
                port: 
                  number: 8000